README.md

Did not see this feature on first sight, and imported {css} from 'glamor' to use it in className props. Read the source code and saw that it's already done inside ToastContainer and Toast components.
Documenting it will save time for future users.
Awesome lib, by the way. Thanks :)

Document possibility to provide a css-in-js object for className props

---

index.d.ts

I found the `fontFamily` property is missing in the type definitions file. Now it's back.

Missing property in the type definitions file

---

index.d.ts

Fixed spelling of exported function `cssTransition`

Update index.d.ts spelling

---

index.d.ts

Now this is possible to use direct types like 
```typescript
import { ToastType, ToastPosition } from 'react-toastify';
// ...
<ToastContainer position={ToastPosition.BOTTOM_RIGHT} />
<Toast type={ToastType.ERROR} />
```
Types in `toast.POSITION` and `toast.TYPE` also more strict than just `string`.

Scrict typings for toast's position and type

---

README.md
src/__tests__/toast.js
src/toast.js

This pull request adds a new option to allow a user to manually set the toastId of the toast they are creating.
In some situations a race condition can occur if multiple async requests are dispatched but are intended to create/update the same toast. Without being able to manually set the toastId, multiple competing requests can generate several toasts at the same time. By manually defining a toastId, we can always be sure to create and edit the same toast.

Added option to manually set a toastId

---

README.md

The indentation for this example was off on the readme. It was bothering me, so I fixed it.
Before:
After:

Fix tabbing on Positioning example in README.md

---

index.d.ts

There should either be an enum or a const, they don't work together.
This causes errors when using Typescript and importing the types

Fix for Toast Position, shouldn't be both const and enum

---

README.md
index.d.ts
src/__tests__/components/ToastContainer.js
src/components/Toast.js
src/components/ToastContainer.js

Added new feature suggested on #310 to display the default `<CloseButton />` element when set `closeButton={true}` on toast options which will supersede the same option on **ToastContainer** when `<ToastContainer closeButton={false} />`.
I also added a new test to test this new feature and updated the readme.

Display default CloseButton when closeButton option set to true 

---

scss/_toast.scss
scss/_variables.scss

Hi,
I noticed the default toast text color was hard-coded to `#aaa` and thus it was not possible to edit the default value from the SCSS. I introduced a new variable `$rt-text-color-default` based on the other existing variables.
Let me know if that sounds good to you or anything else.

Remove hard-coded default toast text color

---

.size-snapshot.json
README.md
src/__tests__/components/ToastContainer.js
src/components/Toast.js
src/components/ToastContainer.js

Hi @fkhadra,
We faced an issue similar to these mentioned here:
https://github.com/fkhadra/react-toastify/issues/134
I tried to fix the issue with no luck, so I ended up with this PR, in theory it pass all the test, and the contribution recommendation, nevertheless let me know what do you think and let me know if I need to add/modify anything :)
Basically I included an explanation about the logic and how to use it in the readme.
The idea is to ensure there is no duplication of any toast inside and outside of a deployed component which use `react-toastify` internally. (parent and child using the library).

Add multiple container support (optional).

---

scss/_toastContainer.scss

**Learn more about contributing [here](https://github.com/fkhadra/react-toastify/blob/master/CONTRIBUTING.md)**

Fix zindex in safari

---

src/__tests__/components/Toast.js
src/__tests__/components/ToastContainer.js
src/components/Toast.js
src/components/ToastContainer.js

**Learn more about contributing [here](https://github.com/fkhadra/react-toastify/blob/master/CONTRIBUTING.md)** 
**Description**
Currently the toast body contains a default …

feat: allow user to override default role

---

src/__tests__/toast.js
src/toast.js

`Ready for Review`
Hello!
First of all, thanks for this amazing tool! So well thought out and extremely robust!
This simple PR is to make the `options` parameter of `toast.update` optional. For the most part, I'm sure we would want to update the content or other configurations, but I noticed for my specific use case, I wanted to extend the autoClose delay of a specific toast message instead of adding more toasts of the same content. But it seems like the `options` parameter is required, because the code assumes it's passed in when accessing `toastId`, and I was seeing errors in my unit tests when I didn't pass it in.
Maybe there is a better way to do this instead of just keeping the empty object
```js
toast.update(toastId, {})
```
Thanks!
Parth

Options parameter of toast.update made optional

---

src/__tests__/toast.js
src/components/ToastContainer.js
src/toast.js

Closes #345 **Update content not working when using multi container**
`toast.js` previously only tracked the last declared `ToastContainer` and this is why it wasn't possible to update toasts fired from inside containers that weren't the last ones.
To solve this I begin tracking all containers inside `toast.js` and using the `containerId` in the options to inform in which containerId is the toast located.
Another possibility would be to care only about the `toastId`. I think we could discuss this here. After we decide which route to take, I can also use this PR to update the docs accordingly.

Allow updating toasts when using multi containers

---

src/__tests__/toast.js
src/toast.js

Closes #363 **toast.configure, multiple containers created**
I did this in the most simple way possible.
Also, we could do another suggestion from the issue that would be to create a flag `isContainerMounted`. But I don't think it would be good to have another multable flag floating around, really... So this is why I used the existing one.

Ensure only one container is mounted when using lazy mounting

---

README.md

Per #371 you cannot dismiss a delayed notification before it appears. This PR adds a note to the docs for *Delay notification appearance* to make that clear.

Add note on behavior of dismiss() when delaying notification appearance

---

src/__tests__/components/Toast.js
src/__tests__/toast.js
src/components/CloseButton.js
src/components/ProgressBar.js
src/components/Toast.js
src/components/ToastContainer.js
src/components/Transitions.js
src/utils/constant.js

since there was a variable in `scss` variables file which can be used for defining a custom namespace for selectors I add support changing namespace inside JS files.
Add RT_NAMESSPACE constant inside the constant file for customizing css selector namespace.

feat: Add RT_Namespace support for customize css selectors namespace

---

src/__tests__/components/ToastContainer.js
src/components/ToastContainer.js

see https://github.com/fkhadra/react-toastify/pull/313#issuecomment-513437356
that change had made it a lot harder to use the default button from the props. This change is there to make it easy to create toast using the button defined in the container. If people want the default button they can easily import it from the callspot.

Fix use closeButton from props when toastClose is true

---

playground/components/ToastCode.js
playground/index.css

This PR adds:
- A monospace font stack and slightly modified styles for the code blocks 017d1f2
- The missing commas to Toast Emitter code sample d852a3c
Currently:
Revised:
Thanks for the work on this library!

Adds missing commas, font stack to playground sample

---

package.json
src/components/ToastContainer.js
src/utils/cssTransition.js
yarn.lock

[react-transition-group 4.0.0](https://github.com/reactjs/react-transition-group/blob/master/CHANGELOG.md#400-2019-04-16) added an ESM build. Bumping the dependency here will allow users to tree shake the react-transition-group components that aren't be used.

bump react-transition-group to v4

---

src/components/CloseButton.js

fixes #259 
This is happening, since the "heavy cross" is an emoji on iOS, and thus won't accept any styling. This changed it to the text version, with the u+FEOE character after it (VS15), as mentioned in https://www.unicode.org/Public/UCD/latest/ucd/StandardizedVariants.txt
8. Format your code with …

fix(closeButton): prevent cross button to be an emoji

---

src/__tests__/components/ToastContainer.js
src/components/ToastContainer.js
src/utils/eventManager.js

In the current version, EventManager handles the `Will_Mount` event after the container has been remounted. In this case, `SHOW` event will not be attached.
I've added the ability to cancel timers that trigger events.

Cancellation WILL_UNMOUNT event when the container is mounted again

---

scss/_toast.scss

Using `flex: 1` evaluates to `flex-basis: 0` which doesn't always work in IE11. Explicitly define `flex-basis: auto`.
Reference: https://makandracards.com/makandra/54644-do-not-use-flex-1-or-flex-basis-0-inside-flex-direction-column-when-you-need-to-support-ie11
8. Format your code with …

Make toast body flex properties more explicit

---

scss/_toastContainer.scss

Fix regression for mobile in case top-center or bottom-center introduced in #430. The translate(50%) was hiding half of the notification.
NIT: Probably yarn install in example should be done on post-install.

Reset translateX for mobile (top/bottom-center)

---

src/hooks/useToastContainer.ts
src/types/index.ts

When toast content is render by component or function, the toast props are passed to component/function.
**Example:**
```
const Msg = ({toastProps, children}) => {
return <div className={`alert alert-${toastProps.variant}`}>{children}</div>;
}; 
toast.success(<Msg>Toast content</Msg>);
```

Add toast props to content callback

---

src/core/toast.tsx
src/index.tsx

`interface ToastPromiseParams` is not visible to external libraries, which causes some typescript error when re-exporting the toast method.

make ToastPromiseParams visible to external libraries

---

src/core/toast.tsx

Fix issue where the toast hangs in the promise `pending` state if the `success`/`error` states are not provided.
Resolves #689.

fix: hanging in promise pending state

---

src/hooks/useToast.ts

This PR stops an error in Chrome: 
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>`
The error is explained at this URL: https://chromestatus.com/feature/5093566007214080

Fix error in Chrome: remove preventDefault from passive listener

---

src/core/toast.tsx
src/types/index.ts

When using `toast.promise` the response typing is not being forwarded to the `success: { render({ data }) ... } ` method. That makes difficult if you want the type safety for the render method
Following the solution from the issue #700 I forked the project and implemented the type forwarding. Most of the work was done by [midwesterntechnology](https://github.com/midwesterntechnology) at the issue. Aside from that, I just had to guarantee that the error interface at the `resolver` was correct without inferring it as `unkown`.
I played with with playground project nothing is broken, as well as all tests are still working as expected

Feature: Toast Promise forwarding types

---

src/components/Icons.tsx
src/components/Toast.tsx
src/components/ToastContainer.tsx
src/types/index.ts

* Allow render numbers as icon
* Pass closeButton from ToastContainer to Toast as-is
* Fix icon types
* Fix closeButton types

Fix closeButton/icon types/rendering

---

package.json

Fixes TypeScript unable to find types when importing react-toastify in ESM module

fix missing types declarations in exports:

---

src/components/ProgressBar.tsx

`type` prop needs to be set as optional in types as it has a default value set.
I stumbled upon this when i opened tests for ProgressBar, they showed missing `type` prop

(chore): change type prop to optional

---

package.json

I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 
Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.
This matches how `types` were already configured for the rest of your entrypoints, this one was the single outlier

Move `types` condition to the front of the `addons/use-notification-center` entry

---

src/components/ToastContainer.tsx
src/hooks/useIsomorphicLayoutEffect.ts

This PR will fix the following issue when running on server side.
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
The `useIsomorphicLayoutEffect` hook fixes this problem by switching between useEffect and useLayoutEffect following the execution environment.

fix: replace useLayoutEffect into useIsomorphicLayoutEffect for server side rendering

---

src/core/store.ts
src/core/toast.cy.tsx

Fix for issue https://github.com/fkhadra/react-toastify/issues/1068
Now how the heck do I squash these 3 ugly commits into 1 proper commit?

Fix: Dismiss all toasts in a single container

---

package.json

This will prevent users from installing the latest version of react-toastify if they're using an unsupported version of React.
I reckon this is the better option vs just getting "useSyncExternalStore is not a function" after installation.

Update react and react-dom peer dependencies to only allow >=18

---

src/core/containerObserver.ts
src/hooks/useToastContainer.ts

Not 100% sure if this is how it should be done, but when I ran things with this change (both locally and with a build and deployment) it seemed to work.
I do get one failing test with NotificationCenter. 
`Failed to resolve import "react-toastify" from "src\addons\use-notification-center\NotificationCenter.cy.tsx".`
I'm not sure what's causing that though.

#1140 - trying to fix the newestOnTop issue
