src/scss/_variables.scss
This enables customisation without touching the original source code.
**Example usage**
```javascript
@include 'my_custom_variables';
@include 'react-toastify/src/scss/main';
```
(reference: [Variable defaults](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Variable_Defaults___default))
=> Use variable defaults in SCSS

README.md, index.d.ts, package-lock.json, src/style.js
As described in #71, when used with bootstrap, react-toastify is displayed under the modal.
This PR adds `zIndex` to the default style to allow easy modification.
=> Add zindex to style helper

src/DefaultTransition.js
Noticed a typo while digging through the DefaultTransition file, thought I'd submit a quick PR for it. Cheers!
=> Fixed a typo in the transition string

index.d.ts
It would help users to avoid typo when setting position
=> Add union types for position

README.md
=> fix indentation

README.md, index.d.ts, src/__tests__/components/__snapshots__/Toast.js.snap, src/components/ProgressBar.js, src/components/Toast.js, src/components/ToastContainer.js
Hey, 
we needed a custom style flag on the ProgressBar of react-toastify for applying a custom theme from material-ui. We thought, this would be a great addition for this package.
I also added documentation for this flag.
Let me know, what you think.
Best Regards, 
Johann
=> Introducing feature/progressbar style

index.d.ts
Fix `type` type in ToastOptions interface to be `TypeOptions`
=> Fix ToastOptions interface

src/__tests__/components/ToastContainer.js, src/components/ToastContainer.js
Fix bug reported on issue #316 
Added an extra test to ensure the expected behaviour.
=> Dismiss id bug fix #316

src/__tests__/components/CloseButton.js, src/components/CloseButton.js, src/components/Toast.js, src/components/ToastContainer.js
#248 #160
Now, user can do something like:
```
toast("Some notification", {
onClick: e => {
// Do something
}
})
```
Or
```
<ToastContainer
....
onClick={e => {
// Default onClick
// Do something
}}
/>
```
Please let me know if you think the API seems good. Hope this is helpful.
=> Add onClick to toast and ToastContainer

README.md
**Learn more about contributing [here](https://github.com/fkhadra/react-toastify/blob/master/CONTRIBUTING.md)**
=> fix: bad apostrophe

README.md
You should use colon instead of "=", because current example gives syntax error
=> Fix problem in code example

README.md
changed tick to quote for copy-paste correctness
=> Minor tick correct

README.md
**Learn more about contributing [here](https://github.com/fkhadra/react-toastify/blob/master/CONTRIBUTING.md)**
=> 💡 Update readme with typo and grammar fixes plus linking to axios

README.md
I can be handy for beginners to see basic set up etc on video. (I used it.)
I am just the beginner, so if my suggestion is not appropriate, you are welcome to criticize :-). …
=> Video tutorial link added to readme file

src/utils/cssTransition.tsx
This fixes #500 
p.s.: Thanks for this amazing project! 🎉
=> Add collapse animation to swipe gesture (#500)

README.md
Removed the white spaces before the exclamation marks from the `README.md` file.
Simple grammar correction.
Updated the `README.md` file with the grammar adjustments.
=> Minor adjustment in README.md exclamation marks spacing

scss/_toast.scss
=> Fix displaying border-radius on mobile

src/core/toast.tsx
- Make the three props in the `toast.promise` object optional to enable greater flexibility
- Add checkbox to the example to disable the pending state
Resolves #644
=> implement optional stages in toast.promise

example/components/App.tsx, example/components/ContainerCode.tsx, example/components/ToastCode.tsx, example/components/constants.ts
Add theme attribute to example code and fix typo on theme select component id.
=> Add theme to example code

src/types/index.ts
=> fix: add function type in `icon` prop #761

src/components/ToastContainer.tsx
=> fix: pass toast styles through

src/types/index.ts
=> loose != lose

build-addons.mjs, package.json
=> use mjs extensions for es modules

src/hooks/useToastContainer.ts
**Learn more about contributing [here](https://github.com/fkhadra/react-toastify/blob/master/CONTRIBUTING.md)**
=> Fixes #772 Memory leak when multiple containers are used

src/hooks/useToastContainer.ts
Finally fixes the memory leak reported in #772
=> Fix remaining memory leak - related to #772

src/core/toast.ts, test/core/toast.test.tsx
This is a suggested minimal fix+test case for #811.
=> Allow toast dismissal without container

scss/_toast.scss
=> fix toast when a word is too long

scss/_toast.scss, src/components/Toast.tsx, test/components/Toast.test.tsx, test/helpers.ts
=> fix cursor when close on click is false

src/types.ts
=> fix: closeOnClick jsdoc to be the same as the real one.
